02shreyansh/CODSOFT

- README.md
I have added the necessary information in the readme.md file. 
Thank you
> Add the Proper readme.md file in it #9

- Landing page/script.js
Closes #26 
Resolve the issue with heroright animation not being visible. Tested and working with the latest version.
https://github.com/02shreyansh/CODSOFT/assets/133508816/1f4cd628-e6f0-4cb1-8c6e-3559c90bb423
> bug: Heroright animation not visible

- Landing page/index.html
> fix: Remove unintended drag functionality for image

- Landing page/index.html
- Landing page/style.css
Closes #12 
Made the necessary changes.
> feat: Add footer section

- README.md
This fix adds a better introduction to the readme file along with some changes in the commands.
> fix: ReadMe fixes

- .vscode/settings.json
- Landing page/enroll.html
- Landing page/index.html
- Landing page/login.css
- Landing page/login.html
- Landing page/style.css
I have added the navbar for login and enroll page with a home button and with the same properties as of on the home page in accordance to the issue #37
> Added the navbar for login and enroll page

- Landing page/index.html
- Landing page/style.css
#38 Added the faq and arranged the contact and form in footer please review my pull request.
> Added faq and improve the footer

- Landing page/blog.css
- Landing page/blog.html
#48 Created a blog page please review my pull request.
> Created a footer in blog page

- Landing page/blog.css
- Landing page/blog.html
- Landing page/enroll.html
- Landing page/feedback.css
- Landing page/feedback.html
- Landing page/index.html
- Landing page/login.css
- Landing page/login.html
- Landing page/planet.css
- Landing page/planet.html
- Landing page/style.css
Closes #59 
Made the necessary changes in the enroll button in all the pages of the site.
https://github.com/02shreyansh/CODSOFT/assets/133508816/f614b98d-5a50-4e82-96d4-af452f9b1c82
> fix: enroll button

- Landing page/blog.html
- Landing page/enroll.html
- Landing page/feedback.html
- Landing page/login.html
- Landing page/new.html
- Landing page/planet.html
#60 Added favicon icon to all the pages , please review my pull request.
> Added favicon icon to all pages

- Landing page/enroll.html
- Landing page/login.css
- Landing page/login.html
#57 Added the footer to both login and enroll page and also i had properly fixed the login and enroll page and now the navbar is properly visible and both these forms are perfectly placed , please review my pull request.
> Added the footer to login and enroll page

- Landing page/blog.css
- Landing page/blog.html
- Landing page/enroll.html
- Landing page/index.html
- Landing page/login.html
- Landing page/scroll.js
- Landing page/style.css
#67 I created a scroll back to top button and added to all the pages , please check and review my pull request.
> Created scroll back to top button

- Landing page/apod.css
- Landing page/apod.html
- Landing page/apod.js
- Landing page/index.html
Added Astronomy picture of the day feature using NASA apod api.
Fixes issue #73
> added apod

- Landing page/enroll.html
> fixed the style of the enrollment page

- Landing page/index.html
- Landing page/index.js
made contact us functional. resolves issue #81
> functional contact us

- Landing page/blog.css
- Landing page/blog.html
Added new blog card : annular eclipse 
fixes issue #86
> add annular eclipse

- Landing page/blog.css
- Landing page/blog.html
> Add international space station card in blogs

- Landing page/enroll.html
fixed broken links in footer.
solves issue #90
> add links in footer

- Landing page/blog.css
- Landing page/blog.html
> add virgin galactic

- Landing page/trailer.html
Revamped the trailer page acc to website's theme and added trailer video embedding from youtube.
resolves #72
> added trailer

- Landing page/blog.css
- Landing page/blog.html
> added wormhole

- Landing page/feedback.css
- Landing page/feedback.html
> fixed distortion on rate us page

- Landing page/blog.css
- Landing page/blog.html
> add pragyan rover

- Landing page/blog.css
- Landing page/blog.html
> Added blog on Small satellite launch vehicle

- Landing page/blog.css
- Landing page/blog.html
Title : Fix footer of the blog page
issue : #98 
Screenshots :
> Fixed Footer of Blog Page

- Landing page/Aditya_L1_blog.html
- Landing page/blog.html
Title : Add a blog page about "Aditya L1"
Issue : #99 
Video : 
[screen-capture (1).webm](https://github.com/02shreyansh/CODSOFT/assets/111490250/ddfbfe30-283b-4703-b7ae-b44acfeeb966)
> Aditya L1 blog page added

- Landing page/blog.css
> fix martian

- Landing page/enroll.html
Title : fix enroll page inputs
Issue : #110 
Screenshots : 
[screen-capture (2).webm](https://github.com/02shreyansh/CODSOFT/assets/111490250/2ac257bd-8a55-42e6-9859-e76b5474dab5)
> Fixed enroll page input

- Landing page/index.html
- Landing page/script.js
Title : New Issue 
Issue : #112 
Video : 
[screen-capture (3).webm](https://github.com/02shreyansh/CODSOFT/assets/111490250/58fcdfe4-f306-4968-a514-5ccaf349eabb)
> Fixed change of planet name with mis-click

- Landing page/Aditya_L1_blog.html
- Landing page/apod.css
- Landing page/apod.html
- Landing page/blog.css
- Landing page/blog.html
- Landing page/chandrayaan.html
- Landing page/enroll.html
- Landing page/feedback.css
- Landing page/feedback.html
- Landing page/mars.html
- Landing page/planet.css
- Landing page/planet.html
- Landing page/ticket.html
- Landing page/trailer.html
- Landing page/worm_blog.html
#118 I had added the menu option to all pages for better UI , please check my pull request.
> Added menu to all the pages

- Landing page/blog.html
fixes #124 
Link to the working video :
https://github.com/02shreyansh/CODSOFT/assets/110532770/20d2fd46-ddce-49f7-ad31-261c85720033
> Blog page revamp and fix

- Landing page/apod.css
- Landing page/apod.html
- Landing page/blog.css
- Landing page/blog.html
- Landing page/chandrayaan.html
- Landing page/mars.html
- Landing page/ticket.html
- Landing page/trailer.html
- Landing page/worm_blog.html
#130 Please check my pull request , i had fixed the issue.
> Add scroll back to top button to all the pages

- Landing page/AnnularEclipse_blog.html
- Landing page/blog.html
Title : Add a dedicated Blog page for "Annular Eclipse" 
Issue : #116
> Annular Blog Added

- Landing page/blog.html
- Landing page/pragyan.html
> Pragyan Rover BlogPage

- Landing page/blog.html
- Landing page/virginGalactic.html
> Virgin Galactic Blog

- Landing page/blog.html
- Landing page/gaganyan.html
> add blogPage for Gaganyaan

- Landing page/planet.html
> fix menu in planets page

- Landing page/JWST_blog.html
- Landing page/blog.html
Title :Add a dedicated web page for "James Web Telescope" Blog
issue : #115 
Screenshots:
> Added Blog on James Webb Space Telescope

- Landing page/index.html
- Landing page/newEnroll.css
- Landing page/newEnroll.html
Created a new Animated Enrollment Form !
Issue No = #132
> Create a new Animated Enrollment Form !

- Landing page/apod.css
- Landing page/blog.css
- Landing page/enroll.html
- Landing page/index.html
- Landing page/mars.html
- Landing page/new.html
- Landing page/ticket.html
- Landing page/trailer.html
#146 I had created a customised scrollbar , please check my pull request.
> Craeted a customised scroll bar and added to all the pages

- Landing page/Sputnik_blog.html
- Landing page/blog.html
Title : Add a new card & Dedicated Blog Page on "Sputnik 1"
Issue : #145 
Screenshots :
> Added Blog on Sputnik 1

- Landing page/ISS_blog.html
- Landing page/blog.html
Title : Add a new card & Dedicated Blog Page on "International Space Station"
Issue :  #144 
Screenshots :
> Added a Blog on International Space Station

- Landing page/feedback.html
- Landing page/newFeed.css
Improve the Rate Us page. Made it completely responsive.
Issue No = #152
> Improve the Rate Us page

- Landing page/create-account.html
- Landing page/login.html
Title : Add a new page/from for "Create an account"
Issue : #151 
Changes : 
1. Added a new page for "Create an Account".
2. Connected it to the login page.
Screenshots:
> Added Create account page

- Landing page/feedback.html
> fix broken links

- Landing page/blog.html
> fix sputnik card

- Landing page/blog.html
- Landing page/sslv.html
> sslv blogpage

- Landing page/blog.html
Added Animation to Blog Page using GSAP.
Issue No = #161 .
> Add Animation to Blog Page

- Landing page/about.html
Title : Improve Footer and Navbar UI of About Us Section
Issue : #164 
Screenshots :
> Improved Footer & Header of About section

- Landing page/login.html
Title :  Add Navbar & Footer to Login page
Issue : #166 
Screenshots :
> Added Footer & Header in Login page

- Landing page/about.html
> fix links in about us

- Landing page/newEnroll.css
> fix menu in enroll page

- Landing page/documentary.html
fixes issue #171 
https://github.com/02shreyansh/CODSOFT/assets/110532770/679fc3e5-2a30-402e-9e19-32bffb86d61d
> documentary page

- Landing page/blog.html
**Title :**  Add hover effect to blog container #186
**Issue:**  #186 
**Fixes**  #186
> Add hover effect to blog container #186

- Landing page/ticket.html
> fix menu in trailer

- Landing page/documentary.html
> add documentary on cosmophobia

- Landing page/blackhole.html
- Landing page/blog.html
> blackhole blog

- Landing page/Aditya_L1_blog.html
- Landing page/about.html
- Landing page/apod.html
- Landing page/feedback.html
- Landing page/login.html
- Landing page/mars.html
- Landing page/planet.html
- Landing page/ticket.html
- Landing page/trailer.html
#177 I added animations to the website , please check my pull request.
> Added animations to all the pages

- Landing page/documentary.html
> spacetime blog

- Landing page/feedback.html
- Landing page/newFeed.css
I had modify the rate us page , please review my pull request
> Modify the rate us page

- Landing page/documentary.html
> add space mystery documentary

- Landing page/blog.html
> fix duplicate images

- Landing page/about.html
Added Customized scrollbar in about us page !
Issue No = #199
> Added Customized scrollbar in about us page

- Landing page/documentary.html
> added documentary on milky way

- Landing page/css/searchengine.css
- Landing page/pages/searchEngine.html
#215 I had fixed the page , please check my pull reuest.
> #215 FIxed the page

- Landing page/pages/blog.html
Add search bar to search blog #211
close #221
> Add search bar to search blog #211

- Landing page/index.html
- Landing page/script/scroll.js
fixes #217 
https://github.com/02shreyansh/CODSOFT/assets/110532770/39a2bba7-f0de-4539-84aa-81dae8fb7424
> add chatbot

- Landing page/pages/Blog/Aditya_L1_blog.html
- Landing page/pages/Blog/AnnularEclipse_blog.html
- Landing page/pages/Blog/ISS_blog.html
- Landing page/pages/Blog/JWST_blog.html
- Landing page/pages/Blog/Sputnik_blog.html
- Landing page/pages/Blog/blackhole.html
- Landing page/pages/Blog/chandrayaan.html
- Landing page/pages/Blog/gaganyan.html
- Landing page/pages/Blog/pragyan.html
- Landing page/pages/Blog/sslv.html
- Landing page/pages/Blog/virginGalactic.html
- Landing page/pages/Blog/worm_blog.html
Added customised scrollbar to all the pages of blog section , please check my pull request
> Added customised scrollbar to all the pages

- Landing page/pages/about.html
- Landing page/pages/apod.html
- Landing page/pages/blog.html
- Landing page/pages/documentary.html
- Landing page/pages/enroll.html
- Landing page/pages/feedback.html
- Landing page/pages/login.html
- Landing page/pages/mars.html
- Landing page/pages/newEnroll.html
- Landing page/pages/planet.html
- Landing page/pages/searchEngine.html
- Landing page/pages/ticket.html
- Landing page/pages/trailer.html
fixes #218
Can you please consider increasing the difficulty tag, It'll help me retain my rank in leaderboard. Thanks.
> fixed all menu's aligment

- Landing page/pages/Blog/AnnularEclipse_blog.html
- Landing page/pages/Blog/ISS_blog.html
- Landing page/pages/Blog/Sputnik_blog.html
- Landing page/pages/Blog/blackhole.html
- Landing page/pages/Blog/chandrayaan.html
- Landing page/pages/Blog/gaganyan.html
- Landing page/pages/Blog/pragyan.html
- Landing page/pages/Blog/sslv.html
- Landing page/pages/Blog/virginGalactic.html
- Landing page/pages/Blog/worm_blog.html
#229 Added animations and scoll button to all the pages of blog section , please check my pull request.
> #229 Added this features

- Landing page/pages/documentary.html
> Add ISS Documentary

- Landing page/pages/documentary.html
> add Alien Documentary

- Landing page/index.html
- Landing page/pages/about.html
- Landing page/pages/apod.html
- Landing page/pages/blog.html
- Landing page/pages/documentary.html
- Landing page/pages/enroll.html
- Landing page/pages/feedback.html
- Landing page/pages/login.html
- Landing page/pages/mars.html
- Landing page/pages/newEnroll.html
- Landing page/pages/searchEngine.html
- Landing page/pages/ticket.html
- Landing page/pages/trailer.html
fixes #219 
please consider increasing difficulty level. Thanks.
fixed footer in all of these pages
> fixed footer links across all pages

- Landing page/pages/documentary.html
fixes #235 
please consider increasing difficulty tag. Thanks.
> fixed distorted cards

- Landing page/pages/documentary.html
> documentary on space Anomalies

- Landing page/pages/documentary.html
> Add documentary on Andromeda

- Landing page/pages/about.html
- Landing page/pages/apod.html
- Landing page/pages/blog.html
- Landing page/pages/documentary.html
- Landing page/pages/feedback.html
- Landing page/pages/login.html
- Landing page/pages/mars.html
- Landing page/pages/new.html
- Landing page/pages/newEnroll.html
- Landing page/pages/planet.html
- Landing page/pages/searchEngine.html
- Landing page/pages/ticket.html
- Landing page/pages/trailer.html
> added chatbot on all pages
